### ISSUE TITLE
建议开启GitHub pages

### ISSUE THREAD

**Issue by bajins** [cznno/doc#8]
这里有多种静态页面的开源项目 [https://www.bajins.com/Web/#静态博客或文档](https://www.bajins.com/Web/#%E9%9D%99%E6%80%81%E5%8D%9A%E5%AE%A2%E6%88%96%E6%96%87%E6%A1%A3)

推荐使用：静态编译VuePress、运行时驱动Docsify

**Comment by cznno** [comment]
懒
